const COLOR_THEME = "#EACE90"
const COLOR_THEME_DARK = "#DEB250"
const COLOR_TEXT = "#2F2F2F"
const COLOR_HEADER_BACKGROUND = "#2F2F2F";
const COLOR_BTN_SELECTED_BACKGROUND = "#FFFFFF12";

export {COLOR_THEME, COLOR_THEME_DARK, COLOR_TEXT, COLOR_HEADER_BACKGROUND, COLOR_BTN_SELECTED_BACKGROUND}